[versions]
kotlin = "2.3.10"
wire = "5.5.0"
wireServer = "1.0.0-alpha04"
coroutine = "1.10.2"
grpc = "1.79.0"
[libraries]
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }
wire-grpc-client = { group = "com.squareup.wire", name = "wire-grpc-client", version.ref = "wire" }
wire-grpc-server = { group = "com.squareup.wiregrpcserver", name = "server", version.ref = "wireServer" }
wire-grpc-server-generator = { group = "com.squareup.wiregrpcserver", name = "server-generator", version.ref = "wireServer" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version = "1.5.0" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
kotlin-coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin-coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
wire = {id = "com.squareup.wire", version.ref = "wire"}